#!/usr/bin/env python3
"""Event world model + cost-to-go learned in imagination + offline planning checks.

1. Event WM f(b, e) -> b' on detected train events (scripts/build_events.py).
2. Cost-to-go h(b, g) by approximate value iteration inside the WM (DeepCubeA-style):
   start codes from the data, goals generated by k random imagined events, target
   y = 0 if b == g else 1 + min_e h_target(f(b, e), g), with a periodically copied target net.
3. Offline checks (privileged button states score the outputs; they are not inputs):
   - h against the true minimal number of presses d* on validation frame pairs, and the sign of
     h's change across each true press (directly comparable with the P1 GCIVL value wall);
   - high-level planning: batch weighted A* over codes between validation frames and on the
     official evaluation tasks; plans are scored by simulating Lights Out with the true buttons
     that event types map to.
"""

from __future__ import annotations

import argparse
import json
import os
import time
from pathlib import Path

import numpy as np

from common import load_code, save_json, size_of, tokens
from lightsout import min_presses, press
from planner import bwas, make_costtogo, make_event_wm

BINS = ((1, 2), (3, 4), (5, 6), (7, 8), (9, 12), (13, 99))


def spearman(x, y):
    rx, ry = np.argsort(np.argsort(x)), np.argsort(np.argsort(y))
    return float(np.corrcoef(rx, ry)[0, 1])


def simulate(state, events, type_to_button, rows, cols):
    s = state.astype(np.uint8)
    for e in events:
        s = press(s, type_to_button[e], rows, cols)
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--events", type=Path, required=True, help="build_events.py output dir")
    ap.add_argument("--cache", type=Path, required=True)
    ap.add_argument("--env", required=True)
    ap.add_argument("--code", type=Path, required=True)
    ap.add_argument("--tasks", type=Path, required=True, help="inventory tasks_<size>.npz")
    ap.add_argument("--wm-steps", type=int, default=6000)
    ap.add_argument("--h-steps", type=int, default=100000)
    ap.add_argument("--h-batch", type=int, default=1024)
    ap.add_argument("--h-hidden", type=int, default=2048)
    ap.add_argument("--h-xor", action="store_true", help="add b xor g features to the cost-to-go input")
    ap.add_argument("--kmax", type=int, default=30)
    ap.add_argument("--target-every", type=int, default=1000)
    ap.add_argument("--pairs-per-bin", type=int, default=40)
    ap.add_argument("--out", type=Path, required=True)
    a = ap.parse_args()
    if "SLURM_JOB_ID" not in os.environ:
        raise RuntimeError("runs under sbatch")
    import torch
    import torch.nn.functional as F

    torch.manual_seed(0)
    rng = np.random.default_rng(0)
    dev = "cuda"
    rows, cols = size_of(a.env)
    t0 = time.time()
    tr, va = np.load(a.events / "events_train.npz"), np.load(a.events / "events_val.npz")
    vocab = np.load(a.events / "vocab.npy")
    rep = json.loads((a.events / "events_report.json").read_text())
    type_to_button = rep["train"]["type_to_button"]                 # privileged, scoring only
    E, K = vocab.shape
    res = {"events": E, "bits": K}
    a.out.mkdir(parents=True, exist_ok=True)

    # 1. Event world model.
    wm = make_event_wm(K, E).to(dev)
    m = tr["e"] >= 0
    Xb, Xe, Y = (torch.as_tensor(tr[k][m], device=dev) for k in ("before", "e", "after"))
    opt = torch.optim.AdamW(wm.parameters(), lr=1e-3, weight_decay=1e-4)
    for step in range(a.wm_steps):
        i = torch.randint(0, len(Xb), (1024,), device=dev)
        loss = F.binary_cross_entropy_with_logits(wm(Xb[i], Xe[i]), Y[i].float())
        opt.zero_grad(set_to_none=True)
        loss.backward()
        opt.step()
    wm.eval()
    mv = va["e"] >= 0
    with torch.no_grad():
        pv = (wm(torch.as_tensor(va["before"][mv], device=dev), torch.as_tensor(va["e"][mv], device=dev)) > 0).cpu().numpy()
    res["wm_val_exact"] = float((pv == va["after"][mv]).all(1).mean())
    res["wm_val_bit"] = float((pv == va["after"][mv]).mean())
    res["wm_val_events"] = int(mv.sum())
    print({"wm": res, "min": round((time.time() - t0) / 60, 1)}, flush=True)

    # 2. Cost-to-go by approximate value iteration in the world model.
    pool = torch.as_tensor(np.unique(tr["codes"][rng.integers(0, len(tr["codes"]), 400_000)], axis=0), device=dev)
    h = make_costtogo(K, a.h_hidden, a.h_xor).to(dev)
    h_tgt = make_costtogo(K, a.h_hidden, a.h_xor).to(dev)
    h_tgt.load_state_dict(h.state_dict())
    opt = torch.optim.AdamW(h.parameters(), lr=3e-4, weight_decay=1e-5)
    hlog = []
    B = a.h_batch
    for step in range(a.h_steps):
        b = pool[torch.randint(0, len(pool), (B,), device=dev)]
        k = torch.randint(0, a.kmax + 1, (B,), device=dev)
        g = b.clone()
        with torch.no_grad():
            for j in range(a.kmax):
                act = k > j
                if not act.any():
                    break
                ev = torch.randint(0, E, (int(act.sum()),), device=dev)
                g[act] = (wm(g[act], ev) > 0).to(torch.uint8)
            ch = wm.successors(b)                                        # (B, E, K)
            gg = g.unsqueeze(1).expand_as(ch)
            with torch.autocast("cuda", dtype=torch.bfloat16):
                hc = h_tgt(ch.reshape(-1, K), gg.reshape(-1, K)).view(B, E).float()
            hc = hc.masked_fill((ch == gg).all(-1), 0.0)
            y = (1 + hc.min(1).values).clamp(max=a.kmax + 5)
            y = y.masked_fill((b == g).all(-1), 0.0)
        loss = F.mse_loss(h(b, g), y)
        opt.zero_grad(set_to_none=True)
        loss.backward()
        opt.step()
        if (step + 1) % a.target_every == 0:
            h_tgt.load_state_dict(h.state_dict())
        if step % 2000 == 0 or step == a.h_steps - 1:
            hlog.append({"step": step, "loss": loss.item(), "y_mean": y.mean().item(), "min": round((time.time() - t0) / 60, 1)})
            print(hlog[-1], flush=True)
    h.eval()
    res["h_log"] = hlog
    torch.save({"wm": wm.state_dict(), "h": h.state_dict(), "h_hidden": a.h_hidden, "h_xor": a.h_xor,
                "events": E, "bits": K, "vocab": vocab,
                "bit_mask": np.load(a.events / "bit_mask.npy"), "code": str(a.code), "type_to_button": type_to_button},
               a.out / "planner.pt")

    # 3a. h vs true distance on validation frames (privileged scoring).
    S = np.load(a.cache / "val_button_states.npy").astype(np.uint8)
    C = va["codes"]
    n = len(C)
    i, j = rng.integers(0, n, 20000), rng.integers(0, n, 20000)
    d = np.array([min_presses(S[x], S[y], rows, cols) for x, y in zip(i, j)])
    with torch.no_grad():
        hv = h(torch.as_tensor(C[i], device=dev), torch.as_tensor(C[j], device=dev)).cpu().numpy()
    res["h_spearman_dstar"] = spearman(hv, d)
    res["h_mean_by_dstar"] = {int(x): float(hv[d == x].mean()) for x in np.unique(d)}
    vterm = np.load(a.cache / "val_terminals.npy")
    ep_v = np.concatenate([[0], np.cumsum(vterm[:-1])])
    ts_all = va["t_start"]
    ev_ok = (va["true_button"] >= 0) & (ts_all >= 10)
    ev_ok[ev_ok] &= ep_v[ts_all[ev_ok] - 10] == ep_v[ts_all[ev_ok]]
    ts_, te_ = ts_all[ev_ok], va["t"][ev_ok]
    pre_t = ts_ - 10                                   # true state before the press (presses are >= 29 steps apart)
    gsel = rng.integers(0, n, len(ts_))
    pre = np.array([min_presses(S[t], S[g], rows, cols) for t, g in zip(pre_t, gsel)])
    post = np.array([min_presses(S[t + 1], S[g], rows, cols) for t, g in zip(te_, gsel)])
    with torch.no_grad():
        gt_ = torch.as_tensor(C[gsel], device=dev)
        h_pre = h(torch.as_tensor(C[ts_], device=dev), gt_).cpu().numpy()
        h_post = h(torch.as_tensor(C[te_ + 1], device=dev), gt_).cpu().numpy()
    agree = np.sign(h_post - h_pre) == np.sign(post - pre)
    res["h_event_sign_by_dstar"] = {f"{lo}-{hi}": {"acc": float(agree[(pre >= lo) & (pre <= hi)].mean()),
                                                   "n": int(((pre >= lo) & (pre <= hi)).sum())}
                                    for lo, hi in BINS if ((pre >= lo) & (pre <= hi)).any()}
    print({k: res[k] for k in ("h_spearman_dstar", "h_event_sign_by_dstar")}, flush=True)

    # 3b. Offline high-level planning between validation frames, by true distance.
    plans = []
    for lo, hi in BINS:
        cand = np.nonzero((d >= lo) & (d <= hi))[0][: a.pairs_per_bin]
        for c in cand:
            ts = time.time()
            path, info = bwas(C[i[c]], C[j[c]], wm, h, dev, batch=256, max_expansions=20000)
            ok = path is not None and bool((simulate(S[i[c]], path, type_to_button, rows, cols) == S[j[c]]).all())
            plans.append({"dstar": int(d[c]), "found": info["found"], "solved": ok,
                          "length": None if path is None else len(path), "expanded": info["expanded"],
                          "sec": round(time.time() - ts, 2)})
    res["offline_plans"] = {f"{lo}-{hi}": {
        "n": len(p), "solved": float(np.mean([x["solved"] for x in p])),
        "length_over_dstar": float(np.mean([x["length"] / x["dstar"] for x in p if x["length"]])) if any(x["length"] for x in p) else None,
        "expanded_median": float(np.median([x["expanded"] for x in p])),
        "sec_median": float(np.median([x["sec"] for x in p]))}
        for lo, hi in BINS for p in [[x for x in plans if lo <= x["dstar"] <= hi]] if p}
    print(res["offline_plans"], flush=True)

    # 3c. Official evaluation tasks: encode the stored init/goal observations, plan, simulate.
    enc, logits, _ = load_code(a.code, dev)
    mask = np.load(a.events / "bit_mask.npy")
    tk = np.load(a.tasks)
    with torch.no_grad():
        def code(obs):
            return (logits(tokens(enc, obs, dev)) > 0).cpu().numpy().astype(np.uint8)[:, mask]
        ci, cg = code(tk["init_ob"]), code(tk["goal_ob"])
    tasks = []
    for n_ in range(len(ci)):
        path, info = bwas(ci[n_], cg[n_], wm, h, dev, batch=256, max_expansions=50000)
        ok = path is not None and bool((simulate(tk["init"][n_], path, type_to_button, rows, cols) == tk["goal"][n_]).all())
        tasks.append({"task": int(tk["task_id"][n_]), "dstar": int(min_presses(tk["init"][n_], tk["goal"][n_], rows, cols)),
                      "found": info["found"], "solved": ok, "length": None if path is None else len(path),
                      "expanded": info["expanded"]})
    res["offline_tasks"] = tasks
    print(tasks, flush=True)
    save_json(a.out / "planner_eval.json", res)


if __name__ == "__main__":
    main()
